export const CREATE_STUDENT = 'POST/CREATE_STUDENT'
export const UPDATE_STUDENT = 'UPDATE/UPDATE_STUDENT'
export const DELETE_STUDENT = 'DELETE/DELETE_STUDENT'
export const ADD_STUDENTS = 'APP/ADD_STUDENTS'