export const CREATE_TASK = 'APP/CREATE_TASK'
export const CLEAR_TASK = 'APP/CLEAR_TASK'
export const SAVE_TASK = 'POST/SAVE_TASK'
export const FETCH_TASKS = 'GET/FETCH_TASKS'
export const FETCH_TASK = 'GET/FETCH_TASK'
export const ADD_TASKS = 'APP/ADD_TASKS'
export const ADD_TASK = 'APP/ADD_TASK'